### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by chimisu** [jovey-zheng/react-start-kit#4]
![qq 20160901153837](https://cloud.githubusercontent.com/assets/12495369/18159184/32c04af6-705a-11e6-9da5-6f5961c52208.png)

**Comment by jovey-zheng** [comment]
@doterme 你修改过什么配置或是文件么

**Comment by chimisu** [comment]
@jovey-zheng 没改过任何东西，Windows 10 64位，nodejs也是官网下的6.5版本，安装之后也没改过什么配置。同事的电脑也试过了，只要npm start，build就报错，Linux下试过了，没有问题。帮忙看看吧。。

**Comment by jovey-zheng** [comment]
@doterme 这个问题在 #5 中已修复，由于我的开发环境都是 Mac OS，不小心忽略了这个问题 :joy:
