### ISSUE TITLE
starter如何应用于生产环境？

### ISSUE THREAD

**Issue by chimisu** [jovey-zheng/react-start-kit#6]
哥们，我看starter是跑在node下，我的生产环境肯定不是node，要么tomcat要么iis这些web server，那我要怎么处理呢？给点建议~

**Comment by jovey-zheng** [comment]
@doterme 这里只是搭一个 node 的环境方便调试，你可以调试完之后 build 部署到生产环境中（构建之后生成的都是静态文件，与普通的 HTML，CSS，JS 没区别）

**Comment by chimisu** [comment]
@jovey-zheng package.json文件存在mv命令，在Windows上是没有这个命令的，我尝试着把这个mv命令拿掉，然后build，生成的文件在_dist文件夹下了，但是文件的名称乱了
![image](https://cloud.githubusercontent.com/assets/12495369/19552715/a06f5fa6-96e3-11e6-8fd3-ec4acf4ffd39.png)

**Comment by jovey-zheng** [comment]
这是正确的文件，文件名用了 hash

**Comment by chimisu** [comment]
@jovey-zheng 那package.json中的mv命令怎么解决啊？Windows上build不过去。

**Comment by jovey-zheng** [comment]
`mv` 可以看作是重命名，这个可以不用，你可以每次手动删除一下 `_dist`
